import { rmSync } from 'node:fs';
import { afterEach, expect, it } from 'vitest';
import { LeaseService } from '../src/index.js';
import { principal, runtimeFixture } from './runtime-fixture.js';
const clean: string[] = [];
afterEach(() => clean.splice(0).forEach((directory) => rmSync(directory, { recursive: true, force: true })));
it('issues one-time hashed fenced leases and rejects stale CAS/subagent/server restart', () => {
  const fixture = runtimeFixture(); clean.push(fixture.dir);
  fixture.db.prepare("INSERT INTO workflow_versions(id,workflow_template_id,version_number,description,safety_baseline_version,content_object_id,content_hash,published_at) VALUES('workflow-v1','workflow',1,'',1,?,'0000000000000000000000000000000000000000000000000000000000000000',?)").run(fixture.object.id, fixture.now);
  fixture.db.prepare("INSERT INTO runs(id,project_id,workflow_version_id,objective,input_envelope,origin_client_type,client_installation_id,origin_session_id,status,updated_at) VALUES('run','project','workflow-v1','','{}','codex','install','root','created',?)").run(fixture.now);
  fixture.db.pragma('user_version = 10');
  const service = new LeaseService(fixture.db, 10, 10_000);
  const lease = service.claim({ runId: 'run', principal, mode: 'start', expectedStatus: 'created', expectedLeaseEpoch: 0 });
  expect((fixture.db.prepare('SELECT lease_token_hash FROM runs').get() as { lease_token_hash: string }).lease_token_hash).not.toContain(lease.leaseToken);
  service.validate({ runId: 'run', leaseEpoch: lease.leaseEpoch, leaseToken: lease.leaseToken }, principal);
  expect(() => service.validate({ runId: 'run', leaseEpoch: 0, leaseToken: lease.leaseToken }, principal)).toThrow('STALE_LEASE');
  expect(() => service.validate({ runId: 'run', leaseEpoch: lease.leaseEpoch, leaseToken: lease.leaseToken }, { ...principal, sessionId: 'sub' })).toThrow('subagent');
  expect(() => new LeaseService(fixture.db, 11).validate({ runId: 'run', leaseEpoch: lease.leaseEpoch, leaseToken: lease.leaseToken }, principal)).toThrow('STALE_LEASE');
  fixture.db.prepare("UPDATE runs SET status='interrupted',lease_token_hash=NULL,lease_expires_at=NULL,lease_holder_session_id=NULL WHERE id='run'").run();
  const recovered = service.claim({ runId: 'run', principal, mode: 'recover', expectedStatus: 'interrupted', expectedLeaseEpoch: 1, recoveryCredential: lease.recoveryCredential });
  expect(recovered.recoveryCredential).not.toBe(lease.recoveryCredential);
  fixture.db.prepare("UPDATE runs SET status='interrupted',lease_token_hash=NULL,lease_expires_at=NULL,lease_holder_session_id=NULL WHERE id='run'").run();
  expect(() => service.claim({ runId: 'run', principal, mode: 'recover', expectedStatus: 'interrupted', expectedLeaseEpoch: 2, recoveryCredential: lease.recoveryCredential })).toThrow('credential mismatch');
  fixture.db.close();
});
