import { Link } from "react-router-dom";
import { Badge } from "../components/badge";
import { EmptyState } from "../components/empty-state";
import { ErrorPanel } from "../components/error-panel";
import { useApi } from "../api/context";
import { useI18n } from "../i18n";
import { useLoad } from "./use-load";
export function OverviewPage() {
  const api = useApi(), { t } = useI18n(), { data: system, error } = useLoad(() => api.system.diagnostics(), [api]), { data: runs, error: runsError } = useLoad(() => api.runs.list(), [api]);
  if (error) return <div className="page"><h1 tabIndex={-1}>{t("dashboard")}</h1><ErrorPanel error={error} /></div>;
  const recent = runs?.slice(0, 5) ?? [];
  return <div className="page"><div className="page-head"><div><span className="eyebrow">{t("localOrchestration")}</span><h1 tabIndex={-1}>{t("workspaceOverview")}</h1><p className="muted">{t("overviewDescription")}</p></div>{system && <Badge>{system.status}</Badge>}</div><div className="grid"><div className="card stat span-3"><strong>{Object.values(system?.run_counts ?? {}).reduce((a,b) => a+b,0)}</strong><span>{t("allRuns")}</span></div><div className="card stat span-3"><strong>{system?.run_counts.running ?? 0}</strong><span>{t("inProgress")}</span></div><div className="card stat span-3"><strong>{system?.run_counts.waiting_for_user ?? 0}</strong><span>{t("waitingConfirmation")}</span></div><div className="card stat span-3"><strong>{system?.adapters.length ?? 0}</strong><span>{t("registeredAdapters")}</span></div><section className="card span-8"><div className="page-head"><h2>{t("recentRuns")}</h2><Link className="row-link" to="/runs">{t("viewAll")} →</Link></div>{runsError ? <ErrorPanel error={runsError} /> : runs === undefined ? <p role="status">{t("loading")}</p> : recent.length ? <div className="table-scroll"><table className="data-table"><thead><tr><th>{t("objective")}</th><th>{t("source")}</th><th>{t("activeStages")}</th><th>{t("status")}</th></tr></thead><tbody>{recent.map((run) => <tr key={run.id}><td><Link className="row-link" to={`/runs/${run.id}`}>{run.objective}</Link></td><td>{run.origin_client_type}</td><td><div className="stage-pills">{run.active_stages.map((stage) => <Badge key={stage}>{stage}</Badge>)}</div></td><td><Badge>{run.status}</Badge></td></tr>)}</tbody></table></div> : <EmptyState title={t("noRuns")} detail={t("noRunsDetail")} />}</section><section className="card span-4"><h2>{t("localService")}</h2><dl className="kv"><dt>{t("webListener")}</dt><dd>{system?.web_listener ?? t("loading")}</dd><dt>SQLite</dt><dd>{system?.database_path ?? t("loading")}</dd><dt>CAS</dt><dd>{system?.cas_status ?? t("loading")}</dd></dl></section></div></div>;
}
