import { closeSync,constants,fstatSync,openSync,readFileSync,realpathSync } from 'node:fs'; import { isAbsolute,relative,resolve } from 'node:path'; import { createHash,randomUUID } from 'node:crypto'; import type Database from 'better-sqlite3'; import type { ContentStore } from '@project-orchestrator/content-store'; import type { WorkspaceState } from './runtime-types.js';
export const workspaceFingerprint=(state:WorkspaceState):string=>createHash('sha256').update(JSON.stringify([state.repositoryHead,state.stagedPatch,state.unstagedPatch,state.untrackedManifest,state.submoduleManifest])).digest('hex');
export class EvidenceService {
 constructor(readonly db:Database.Database,readonly content:ContentStore){}
 recordArtifact(input:{runId:string;stageAttemptId:string;projectRoot:string;sourcePath:string;artifactType:'document'|'log'|'test_evidence'|'file_manifest'|'ui_prototype'|'deployment_record'|'rollback_record'|'other';summary:string;producerRoleVersionId:string;metadata?:unknown}):{id:string;contentObjectId:string}{
  const root=realpathSync(resolve(input.projectRoot));const candidate=resolve(root,input.sourcePath);if(isAbsolute(input.sourcePath)&&!candidate.startsWith(`${root}/`))throw new Error('POLICY_VIOLATION: artifact outside project');let fd:number|undefined;try{fd=openSync(candidate,constants.O_RDONLY|constants.O_NOFOLLOW);const actual=realpathSync(`/proc/self/fd/${fd}`);const rel=relative(root,actual);if(rel.startsWith('..')||isAbsolute(rel))throw new Error('POLICY_VIOLATION: artifact outside project');if(!fstatSync(fd).isFile())throw new Error('ARTIFACT_MISSING: not regular file');const object=this.content.putBytes(readFileSync(fd),'application/octet-stream');const id=randomUUID();this.db.prepare('INSERT INTO artifacts(id,run_id,stage_attempt_id,artifact_type,content_object_id,source_path,summary,producer_role_version_id,metadata_envelope,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,input.runId,input.stageAttemptId,input.artifactType,object.id,input.sourcePath,input.summary,input.producerRoleVersionId,JSON.stringify(input.metadata??{}),new Date().toISOString());return{id,contentObjectId:object.id};}finally{if(fd!==undefined)closeSync(fd);}
 }
 recordCheckpoint(input:{runId:string;stageAttemptId?:string;kind:'run_start'|'before_attempt'|'progress'|'after_attempt';baselineFingerprint:string;state:WorkspaceState}):{id:string;fingerprint:string}{const staged=this.content.putUtf8(input.state.stagedPatch);const unstaged=this.content.putUtf8(input.state.unstagedPatch);const untracked=this.content.putCanonicalJson(input.state.untrackedManifest);const submodule=this.content.putCanonicalJson(input.state.submoduleManifest);const fingerprint=workspaceFingerprint(input.state),id=randomUUID();this.db.prepare('INSERT INTO workspace_checkpoints(id,run_id,stage_attempt_id,checkpoint_kind,baseline_fingerprint,resulting_fingerprint,staged_patch_object_id,unstaged_patch_object_id,untracked_manifest_object_id,submodule_manifest_object_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(id,input.runId,input.stageAttemptId??null,input.kind,input.baselineFingerprint,fingerprint,staged.id,unstaged.id,untracked.id,submodule.id,new Date().toISOString());return{id,fingerprint};}
}
